package com.cisco.spark.android.room;

import android.net.Uri;

/**
 * The backend that owns the space and knows whether a client is in a space and matches tokens
 * generated by a space and picked up by the client
 */
public interface ProximityBackend {

    void announceProximity(String token, AnnounceCallback callback);

    void requestProximityStatus(Uri url, ProximityStatusCallback callback);

}
