package com.cisco.spark.android.room;

import android.net.Uri;

import com.cisco.spark.android.lyra.SpaceResponseCallback;
import com.cisco.spark.android.lyra.model.Link;

/**
 * The backend that owns the space and knows whether a client is in a space and matches tokens
 * generated by a space and picked up by the client
 */
public interface ProximityBackend {

    void announceProximity(String token, AnnounceCallback callback);

    void requestProximityStatus(Uri url, ProximityStatusCallback callback);

    void announceLyraProximity(String token, LyraAnnounceCallback callback);

    void requestAddToSpace(Link spaceLink, Uri deviceUrl, String proof, SpaceResponseCallback callback);

    void requestLyraProximityStatusBySpaceUrl(String spaceUrl, LyraSpaceCallback callback);

    void leaveSpace(String spaceId, String deviceUrl, SpaceResponseCallback callback);

    void requestLyraProximityStatus(Uri deviceUrl, ProximityStatusCallback callback);

}
