package com.cisco.spark.android.metrics.value;

public final class ClientMetricNames {
    public static final String ONBOARDING_VIEWED_GETTING_STARTED = "ob_viewed_get_started";
    public static final String ONBOARDING_VIEWED_TOS = "ob_viewed_terms_of_service";
    public static final String ONBOARDING_VIEWED_PRIVACY = "ob_viewed_privacy_statement";
    public static final String ONBOARDING_VIEWED_NOTICES = "ob_viewed_notices_and_disclaimers";
    public static final String ONBOARDING_VIEWED_NEED_HELP = "ob_viewed_need_help";
    public static final String ONBOARDING_VIEWED_ENTER_EMAIL = "ob_viewed_enter_email";
    public static final String ONBOARDING_ENTERED_EMAIL = "ob_entered_email";
    public static final String ONBOARDING_CONFIRMED_EMAIL = "ob_confirmed_email";
    public static final String ONBOARDING_VIEWED_CHECK_YOUR_EMAIL = "ob_viewed_check_your_email";
    public static final String ONBOARDING_EDITED_EMAIL = "ob_edited_email";
    public static final String ONBOARDING_OPENED_EMAIL = "ob_opened_native_email_app";
    public static final String ONBOARDING_RESENT_EMAIL = "ob_resent_email";
    public static final String ONBOARDING_RESENT_EMAIL_MODAL = "ob_resent_email_modal_ok";
    public static final String ONBOARDING_ALLOWED_APP_OPEN = "ob_allowed_app_open";
    public static final String ONBOARDING_ALLOWED_MICROPHONE = "ob_allowed_microphone";
    public static final String ONBOARDING_VIEWED_CREATE_PROFILE = "ob_viewed_create_profile";
    public static final String ONBOARDING_UPLOADED_AVATAR = "ob_uploaded_avatar";
    public static final String ONBOARDING_ALLOWED_CAMERA = "ob_allowed_camera";
    public static final String ONBOARDING_CREATED_PROFILE = "ob_created_profile";
    public static final String ONBOARDING_VIEWED_CREATE_TEAM = "ob_viewed_create_team";
    public static final String ONBOARDING_CREATED_TEAM = "ob_created_team";
    public static final String ONBOARDING_SKIPPED_CREATE_TEAM = "ob_skipped_create_team";
    public static final String ONBOARDING_VIEWED_CONNECT = "ob_viewed_connect_calendar_and_contacts";
    public static final String ONBOARDING_SELECTED_CONNET = "ob_selected_connet_calendar_and_contacts";
    public static final String ONBOARDING_ALLOWED_CALENDAR = "ob_allowed_calendar";
    public static final String ONBOARDING_DECLINED_CALENDAR = "ob_declined_calendar";
    public static final String ONBOARDING_ALLOWED_CONTACTS = "ob_allowed_contacts";
    public static final String ONBOARDING_DECLINED_CONTACTS = "ob_declined_contacts";
    public static final String ONBOARDING_SELECTED_ENTER_EMAILS_MANUALLY = "ob_selected_enter_emails_manually";
    public static final String ONBOARDING_VIEWED_INVITE_TO_TEAM = "ob_viewed_invite_to_team";
    public static final String ONBOARDING_SKIPPED_INVITE_TO_TEAM = "ob_skipped_invite_to_team";
    public static final String ONBOARDING_SELECTED_CONTACT = "ob_selected_contact";
    public static final String ONBOARDING_INVITED_PEOPLE_TO_TEAM = "ob_invited_people_to_team";
    public static final String ONBOARDING_ACK_TEAM_ROOMS_COACHMARK = "ob_acknowledged_team_rooms_coach_mark";
    public static final String ONBOARDING_ACK_TEAM_MEMBER_COACHMARK = "ob_acknowledged_team_members_coach_mark";
    public static final String ONBOARDING_ACK_RECENTS_COACHMARK = "ob_acknowledged_recents_coach_mark";
    public static final String ONBOARDING_ACK_SEND_MESSAGE_COACHMARK = "ob_acknowledged_send_message_coach_mark";
    public static final String ONBOARDING_ACK_FLAGS_COACHMARK = "ob_acknowledged_flags_coach_mark";
}
